before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: lPi+Va9AIfh3DG95jgAKt69+Wemr0fsQfAY4D5cEtUWr8k47MALAeRQaBOVoSzdQ86FyOmVCo3UITmFIGnnDmJ7lzWWiNn3jPQu6LuvrKvkENNinnt4SJ9vqPwoVdqqwunXn5lfI+sDvTCPl0YQOzyDNW7tTvPP2Di0wiy0O7C5wRHLgicfzJ9LWXio5GhGCRU0uoAiRNLqK3asKLbDAAoxJhmB3SIZLL4fg+m8Jcbo6sz1V2j3x2Gw5vCIhghaQ149QGKbMuVHEn9ohJXtFOb4Ap6bIWuxnvXrg5lFjY5ktTKWXvOrsi+km348XYaTDtYlOou2RWITGdIQSMVS563vBb58ofomNDU2Rv6kUSlLRYtWRCXZy170JGvcrWvOqVygedmuAIZywGN/lj3ACwjKPkVTQtU/YBp466QxNRKzF6uWVq/xs0dCGBRD1GC19QG5lquiD0rdu9aOgO/JIZDjhih1K5ZLKmSzDP1Xz1681u/cidtHn0bvvABEEdmF/lM/b+pU4WyPVmGGQhyDxdAiKETpvfrGqpWomcR1zeRdVF6MQl7RSSMf9KPpdFE+rHbtkjyY94Y2JMmKharcvReJYQUO01BXmolxTXKBQEZ4mtj0VgCqwqLaxrBENX0pHrAbYDxepNYwmM+N8Ttu9SQsGqyd/e+8++QdRxtHNpow= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
